name: Pypi publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  publish:

    # Trigger only if the commit starts with a number (i.e. semantic release version number)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.author.name, 'semantic-release')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: 
      name: pypi
      url: https://pypi.org/p/pnt_datasets
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:

      - name: PyPi publish
        uses: pypa/gh-action-pypi-publish@release/v1
        
